-- =============================================================================
-- Script DDL generado a partir del ERD (Mermaid)
-- Motor: PostgreSQL
-- Dominio: Sistema de reclutamiento y gestión de entrevistas
--
-- Normalización: 1FN, 2FN, 3FN y FNBC
-- - company.description centraliza el dato antes redundante en position
-- - Claves candidatas explícitas para determinantes funcionales del dominio
-- =============================================================================

BEGIN;

-- ---------------------------------------------------------------------------
-- Tablas base (sin dependencias externas)
-- ---------------------------------------------------------------------------

CREATE TABLE company (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    description TEXT
);

CREATE TABLE interview_flow (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description VARCHAR(255) NOT NULL
);

CREATE TABLE interview_type (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100) NOT NULL,
    description TEXT,

    CONSTRAINT uq_interview_type_name
        UNIQUE (name)
);

CREATE TABLE candidate (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    last_name  VARCHAR(100) NOT NULL,
    email      VARCHAR(255) NOT NULL,
    phone      VARCHAR(50),
    address    VARCHAR(255),

    CONSTRAINT uq_candidate_email
        UNIQUE (email)
);

-- ---------------------------------------------------------------------------
-- Tablas con dependencias de primer nivel
-- ---------------------------------------------------------------------------

CREATE TABLE employee (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id INTEGER NOT NULL,
    name       VARCHAR(255) NOT NULL,
    email      VARCHAR(255) NOT NULL,
    role       VARCHAR(100) NOT NULL,
    is_active  BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT fk_employee_company
        FOREIGN KEY (company_id) REFERENCES company (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT uq_employee_company_email
        UNIQUE (company_id, email)
);

CREATE TABLE interview_step (
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    interview_flow_id INTEGER NOT NULL,
    interview_type_id INTEGER NOT NULL,
    name              VARCHAR(150) NOT NULL,
    order_index       INTEGER NOT NULL,

    CONSTRAINT fk_interview_step_flow
        FOREIGN KEY (interview_flow_id) REFERENCES interview_flow (id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_interview_step_type
        FOREIGN KEY (interview_type_id) REFERENCES interview_type (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT uq_interview_step_flow_order
        UNIQUE (interview_flow_id, order_index),

    CONSTRAINT uq_interview_step_type
        UNIQUE (interview_type_id),

    CONSTRAINT chk_interview_step_order_index
        CHECK (order_index >= 0)
);

CREATE TABLE position (
    id                   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id           INTEGER NOT NULL,
    interview_flow_id    INTEGER NOT NULL,
    title                VARCHAR(200) NOT NULL,
    description          TEXT,
    status               VARCHAR(50) NOT NULL,
    is_visible           BOOLEAN NOT NULL DEFAULT TRUE,
    location             VARCHAR(255),
    job_description      TEXT,
    requirements         TEXT,
    responsibilities     TEXT,
    salary_min           NUMERIC(12, 2),
    salary_max           NUMERIC(12, 2),
    employment_type      VARCHAR(50),
    benefits             TEXT,
    application_deadline DATE,
    contact_info         VARCHAR(255),

    CONSTRAINT fk_position_company
        FOREIGN KEY (company_id) REFERENCES company (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_position_interview_flow
        FOREIGN KEY (interview_flow_id) REFERENCES interview_flow (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT uq_position_interview_flow
        UNIQUE (interview_flow_id),

    CONSTRAINT chk_position_salary_range
        CHECK (
            salary_min IS NULL
            OR salary_max IS NULL
            OR salary_min <= salary_max
        )
);

-- ---------------------------------------------------------------------------
-- Tablas transaccionales
-- ---------------------------------------------------------------------------

CREATE TABLE application (
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    position_id      INTEGER NOT NULL,
    candidate_id     INTEGER NOT NULL,
    application_date DATE NOT NULL DEFAULT CURRENT_DATE,
    status           VARCHAR(50) NOT NULL,
    notes            TEXT,

    CONSTRAINT fk_application_position
        FOREIGN KEY (position_id) REFERENCES position (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_application_candidate
        FOREIGN KEY (candidate_id) REFERENCES candidate (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT uq_application_position_candidate
        UNIQUE (position_id, candidate_id)
);

CREATE TABLE interview (
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id    INTEGER NOT NULL,
    interview_step_id INTEGER NOT NULL,
    employee_id       INTEGER NOT NULL,
    interview_date    DATE NOT NULL,
    result            VARCHAR(50),
    score             INTEGER,
    notes             TEXT,

    CONSTRAINT fk_interview_application
        FOREIGN KEY (application_id) REFERENCES application (id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_interview_step
        FOREIGN KEY (interview_step_id) REFERENCES interview_step (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_interview_employee
        FOREIGN KEY (employee_id) REFERENCES employee (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT uq_interview_application_step
        UNIQUE (application_id, interview_step_id),

    CONSTRAINT chk_interview_score
        CHECK (score IS NULL OR (score >= 0 AND score <= 100))
);

-- ---------------------------------------------------------------------------
-- Índices de soporte (FKs, consultas frecuentes y claves alternativas)
-- ---------------------------------------------------------------------------

CREATE INDEX idx_employee_company_id ON employee (company_id);

CREATE INDEX idx_employee_company_active ON employee (company_id, is_active)
    WHERE is_active = TRUE;

CREATE INDEX idx_interview_step_flow_id ON interview_step (interview_flow_id);

CREATE INDEX idx_position_company_id ON position (company_id);

CREATE INDEX idx_position_company_visible_status
    ON position (company_id, is_visible, status);

CREATE INDEX idx_position_application_deadline ON position (application_deadline);

CREATE INDEX idx_application_candidate_id ON application (candidate_id);

CREATE INDEX idx_application_position_status
    ON application (position_id, status);

CREATE INDEX idx_application_date ON application (application_date);

CREATE INDEX idx_interview_interview_step_id ON interview (interview_step_id);

CREATE INDEX idx_interview_employee_id ON interview (employee_id);

CREATE INDEX idx_interview_interview_date ON interview (interview_date);

COMMIT;
