-- =============================================================================
-- Fase 1: Catálogos base
-- Entidades ERD: COMPANY, INTERVIEW_FLOW, INTERVIEW_TYPE
-- Prerequisitos: Fase 0 completada (backup realizado)
-- =============================================================================

BEGIN;

CREATE TABLE IF NOT EXISTS company (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    description TEXT
);

CREATE TABLE IF NOT EXISTS interview_flow (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS interview_type (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100) NOT NULL,
    description TEXT,

    CONSTRAINT uq_interview_type_name
        UNIQUE (name)
);

COMMIT;
