-- =============================================================================
-- Fase 2: Migración de CANDIDATE
-- Entidad ERD: CANDIDATE (firstName/lastName → first_name/last_name)
-- Prerequisitos: Fase 1 completada
-- Preserva: Education, WorkExperience, Resume (satélites Prisma)
-- =============================================================================

BEGIN;

-- ---------------------------------------------------------------------------
-- Escenario A: existe tabla legacy "Candidate" (Prisma) → renombrado in-place
-- ---------------------------------------------------------------------------
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'Candidate'
    ) AND NOT EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'candidate'
    ) THEN
        ALTER TABLE "Candidate" RENAME TO candidate;
        ALTER TABLE candidate RENAME COLUMN "firstName" TO first_name;
        ALTER TABLE candidate RENAME COLUMN "lastName"  TO last_name;

        ALTER TABLE candidate
            ALTER COLUMN phone   TYPE VARCHAR(50),
            ALTER COLUMN address TYPE VARCHAR(255);
    END IF;
END $$;

-- ---------------------------------------------------------------------------
-- Escenario B: BD nueva sin legacy → crear candidate vacía
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS candidate (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    last_name  VARCHAR(100) NOT NULL,
    email      VARCHAR(255) NOT NULL,
    phone      VARCHAR(50),
    address    VARCHAR(255)
);

-- ---------------------------------------------------------------------------
-- Unicidad de email (ERD + integridad)
-- ---------------------------------------------------------------------------
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'uq_candidate_email' AND conrelid = 'candidate'::regclass
    ) THEN
        ALTER TABLE candidate ADD CONSTRAINT uq_candidate_email UNIQUE (email);
    END IF;
END $$;

-- ---------------------------------------------------------------------------
-- Repoint FKs de tablas satélite Prisma (si existen con columnas legacy)
-- ---------------------------------------------------------------------------
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'Education'
          AND column_name = 'candidateId'
    ) THEN
        ALTER TABLE "Education" RENAME COLUMN "candidateId" TO candidate_id;
    END IF;

    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'WorkExperience'
          AND column_name = 'candidateId'
    ) THEN
        ALTER TABLE "WorkExperience" RENAME COLUMN "candidateId" TO candidate_id;
    END IF;

    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'Resume'
          AND column_name = 'candidateId'
    ) THEN
        ALTER TABLE "Resume" RENAME COLUMN "candidateId" TO candidate_id;
    END IF;
END $$;

COMMIT;
