-- =============================================================================
-- Fase 3: Entidades operativas
-- Entidades ERD: EMPLOYEE, INTERVIEW_STEP, POSITION
-- Relaciones: COMPANY→EMPLOYEE, COMPANY→POSITION, INTERVIEW_FLOW→INTERVIEW_STEP,
--             INTERVIEW_STEP↔INTERVIEW_TYPE (1:1), POSITION↔INTERVIEW_FLOW (1:1)
-- Prerequisitos: Fases 1 y 2 completadas
-- =============================================================================

BEGIN;

CREATE TABLE IF NOT EXISTS employee (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id INTEGER NOT NULL,
    name       VARCHAR(255) NOT NULL,
    email      VARCHAR(255) NOT NULL,
    role       VARCHAR(100) NOT NULL,
    is_active  BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT fk_employee_company
        FOREIGN KEY (company_id) REFERENCES company (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT uq_employee_company_email
        UNIQUE (company_id, email)
);

CREATE TABLE IF NOT EXISTS interview_step (
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    interview_flow_id INTEGER NOT NULL,
    interview_type_id INTEGER NOT NULL,
    name              VARCHAR(150) NOT NULL,
    order_index       INTEGER NOT NULL,

    CONSTRAINT fk_interview_step_flow
        FOREIGN KEY (interview_flow_id) REFERENCES interview_flow (id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_interview_step_type
        FOREIGN KEY (interview_type_id) REFERENCES interview_type (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT uq_interview_step_flow_order
        UNIQUE (interview_flow_id, order_index),

    CONSTRAINT uq_interview_step_type
        UNIQUE (interview_type_id),

    CONSTRAINT chk_interview_step_order_index
        CHECK (order_index >= 0)
);

CREATE TABLE IF NOT EXISTS position (
    id                   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id           INTEGER NOT NULL,
    interview_flow_id    INTEGER NOT NULL,
    title                VARCHAR(200) NOT NULL,
    description          TEXT,
    status               VARCHAR(50) NOT NULL,
    is_visible           BOOLEAN NOT NULL DEFAULT TRUE,
    location             VARCHAR(255),
    job_description      TEXT,
    requirements         TEXT,
    responsibilities     TEXT,
    salary_min           NUMERIC(12, 2),
    salary_max           NUMERIC(12, 2),
    employment_type      VARCHAR(50),
    benefits             TEXT,
    application_deadline DATE,
    contact_info         VARCHAR(255),

    CONSTRAINT fk_position_company
        FOREIGN KEY (company_id) REFERENCES company (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_position_interview_flow
        FOREIGN KEY (interview_flow_id) REFERENCES interview_flow (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT uq_position_interview_flow
        UNIQUE (interview_flow_id),

    CONSTRAINT chk_position_salary_range
        CHECK (
            salary_min IS NULL
            OR salary_max IS NULL
            OR salary_min <= salary_max
        )
);

COMMIT;
