-- =============================================================================
-- Fase 4: Capa transaccional
-- Entidades ERD: APPLICATION, INTERVIEW
-- Relaciones: POSITION→APPLICATION, CANDIDATE→APPLICATION,
--             APPLICATION→INTERVIEW, INTERVIEW→INTERVIEW_STEP, EMPLOYEE→INTERVIEW
-- Prerequisitos: Fases 1, 2 y 3 completadas
-- =============================================================================

BEGIN;

CREATE TABLE IF NOT EXISTS application (
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    position_id      INTEGER NOT NULL,
    candidate_id     INTEGER NOT NULL,
    application_date DATE NOT NULL DEFAULT CURRENT_DATE,
    status           VARCHAR(50) NOT NULL,
    notes            TEXT,

    CONSTRAINT fk_application_position
        FOREIGN KEY (position_id) REFERENCES position (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_application_candidate
        FOREIGN KEY (candidate_id) REFERENCES candidate (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT uq_application_position_candidate
        UNIQUE (position_id, candidate_id)
);

CREATE TABLE IF NOT EXISTS interview (
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id    INTEGER NOT NULL,
    interview_step_id INTEGER NOT NULL,
    employee_id       INTEGER NOT NULL,
    interview_date    DATE NOT NULL,
    result            VARCHAR(50),
    score             INTEGER,
    notes             TEXT,

    CONSTRAINT fk_interview_application
        FOREIGN KEY (application_id) REFERENCES application (id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_interview_step
        FOREIGN KEY (interview_step_id) REFERENCES interview_step (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_interview_employee
        FOREIGN KEY (employee_id) REFERENCES employee (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT uq_interview_application_step
        UNIQUE (application_id, interview_step_id),

    CONSTRAINT chk_interview_score
        CHECK (score IS NULL OR (score >= 0 AND score <= 100))
);

COMMIT;
